// List of indicators matches js (0 to 75)
const indicators = [
    "Household access to discretionary funds",
    "Community financial health",
    "Local government financial capacity",
    "Public infrastructure maintenance budget",
    "Climate change adaptation planning and investment",
    "Business continuity during floods",
    "Business continuity during heatwave",
    "Household income continuity during flood",
    "Household income continuity during heatwave",
    "Flood risk reduction investment",
    "Heatwave risk reduction investment",
    "Disaster insurance",
    "Disaster recovery budget",
    "Disaster recovery budget",
    "Heatwave action-plan budget",
    "Secondary school attendance",
    "Food availability",
    "First aid knowledge",
    "Awareness of the need for climate change action",
    "Awareness of climate change risk on floods",
    "Awareness of climate change risk on heatwaves",
    "Awareness of how nature mitigates risk during floods",
    "Awareness of how nature mitigates risk during heatwaves",
    "Hazard exposure awareness",
    "Hazard vulnerability awareness",
    "Evacuation and safety knowledge",
    "Unsafe water awareness",
    "Heatwave protection knowledge",
    "Worker protection for heatwaves",
    "Tree cover",
    "Permeable surfaces",
    "Land use planning",
    "Resource management",
    "Land/water interface health",
    "Ecological management for flood disaster risk reduction",
    "Ecological management for heatwave disaster risk reduction",
    "Energy supply continuity",
    "Transportation system continuity",
    "Communication systems continuity",
    "Flood early warning",
    "Heatwave early warning",
    "Continuity of education during floods",
    "Continuity of education during heatwaves",
    "Emergency infrastructure and supplies during floods",
    "Emergency infrastructure and supplies during heatwaves",
    "Continuity of healthcare during disaster during floods",
    "Continuity of healthcare during disaster during heatwaves",
    "Forecasting for floods",
    "Forecasting for heatwaves",
    "Household protection and adaptation on floods",
    "Household protection and adaptation on heatwaves",
    "Availability of clean, safe water during floods",
    "Availability of clean, safe water during heatwaves",
    "Waste management and risk",
    "Large scale flood protection",
    "Mutual support",
    "Social inclusiveness of disaster risk management",
    "Community safety",
    "Local leadership",
    "Disaster response personnel",
    "Healthcare accessibility",
    "Trust in local authorities",
    "Intra-community equity",
    "Inter-community equity",
    "Risk reduction planning for floods",
    "Risk reduction planning for heatwaves",
    "Response planning for floods",
    "Response planning for heatwaves",
    "Family violence and response planning during floods",
    "Family violence and response planning during heatwaves",
    "Stakeholder engagement in risk management for floods",
    "Stakeholder engagement in risk management for heatwaves",
    "Flood risk mapping",
    "Heatwave risk mapping",
    "Flood disaster impact data collection and use",
    "Heatwave disaster impact data collection and use"
];

// List of capital types
const capitals = ['human', 'social', 'physical', 'natural', 'financial'];

// List of resilience properties
const resilienceProperties = ['robustness', 'redundancy', 'resourcefulness', 'rapidity'];

// Correct matches for 76 indicators
const correctMatches = [
    { indicator: 0, capital: 'financial', resilience: 'resourcefulness', name: "Household access to discretionary funds" },
    { indicator: 1, capital: 'financial', resilience: 'robustness', name: "Community financial health" },
    { indicator: 2, capital: 'financial', resilience: 'resourcefulness', name: "Local government financial capacity" },
    { indicator: 3, capital: 'financial', resilience: 'robustness', name: "Public infrastructure maintenance budget" },
    { indicator: 4, capital: 'financial', resilience: 'robustness', name: "Climate change adaptation planning and investment" },
    { indicator: 5, capital: 'financial', resilience: 'rapidity', name: "Business continuity during floods" },
    { indicator: 6, capital: 'financial', resilience: 'rapidity', name: "Business continuity during heatwave" },
    { indicator: 7, capital: 'financial', resilience: 'rapidity', name: "Household income continuity during flood" },
    { indicator: 8, capital: 'financial', resilience: 'rapidity', name: "Household income continuity during heatwave" },
    { indicator: 9, capital: 'financial', resilience: 'rapidity', name: "Flood risk reduction investment" },
    { indicator: 10, capital: 'financial', resilience: 'rapidity', name: "Heatwave risk reduction investment" },
    { indicator: 11, capital: 'financial', resilience: 'rapidity', name: "Disaster insurance" },
    { indicator: 12, capital: 'financial', resilience: 'rapidity', name: "Disaster recovery budget" },
    { indicator: 13, capital: 'financial', resilience: 'resourcefulness', name: "Disaster recovery budget" },
    { indicator: 14, capital: 'financial', resilience: 'rapidity', name: "Heatwave action-plan budget" },
    { indicator: 15, capital: 'human', resilience: 'resourcefulness', name: "Secondary school attendance" },
    { indicator: 16, capital: 'human', resilience: 'robustness', name: "Food availability" },
    { indicator: 17, capital: 'human', resilience: 'resourcefulness', name: "First aid knowledge" },
    { indicator: 18, capital: 'human', resilience: 'rapidity', name: "Awareness of the need for climate change action" },
    { indicator: 19, capital: 'human', resilience: 'robustness', name: "Awareness of climate change risk on floods" },
    { indicator: 20, capital: 'human', resilience: 'robustness', name: "Awareness of climate change risk on heatwaves" },
    { indicator: 21, capital: 'human', resilience: 'redundancy', name: "Awareness of how nature mitigates risk during floods" },
    { indicator: 22, capital: 'human', resilience: 'redundancy', name: "Awareness of how nature mitigates risk during heatwaves" },
    { indicator: 23, capital: 'human', resilience: 'resourcefulness', name: "Hazard exposure awareness" },
    { indicator: 24, capital: 'human', resilience: 'resourcefulness', name: "Hazard vulnerability awareness" },
    { indicator: 25, capital: 'human', resilience: 'resourcefulness', name: "Evacuation and safety knowledge" },
    { indicator: 26, capital: 'human', resilience: 'robustness', name: "Unsafe water awareness" },
    { indicator: 27, capital: 'human', resilience: 'resourcefulness', name: "Heatwave protection knowledge" },
    { indicator: 28, capital: 'human', resilience: 'robustness', name: "Worker protection for heatwaves" },
    { indicator: 29, capital: 'natural', resilience: 'redundancy', name: "Tree cover" },
    { indicator: 30, capital: 'natural', resilience: 'redundancy', name: "Permeable surfaces" },
    { indicator: 31, capital: 'natural', resilience: 'redundancy', name: "Land use planning" },
    { indicator: 32, capital: 'natural', resilience: 'resourcefulness', name: "Resource management" },
    { indicator: 33, capital: 'natural', resilience: 'redundancy', name: "Land/water interface health" },
    { indicator: 34, capital: 'natural', resilience: 'redundancy', name: "Ecological management for flood disaster risk reduction" },
    { indicator: 35, capital: 'natural', resilience: 'redundancy', name: "Ecological management for heatwave disaster risk reduction" },
    { indicator: 36, capital: 'physical', resilience: 'redundancy', name: "Energy supply continuity" },
    { indicator: 37, capital: 'physical', resilience: 'redundancy', name: "Transportation system continuity" },
    { indicator: 38, capital: 'physical', resilience: 'robustness', name: "Communication systems continuity" },
    { indicator: 39, capital: 'physical', resilience: 'rapidity', name: "Flood early warning" },
    { indicator: 40, capital: 'physical', resilience: 'rapidity', name: "Heatwave early warning" },
    { indicator: 41, capital: 'physical', resilience: 'rapidity', name: "Continuity of education during floods" },
    { indicator: 42, capital: 'physical', resilience: 'rapidity', name: "Continuity of education during heatwaves" },
    { indicator: 43, capital: 'physical', resilience: 'rapidity', name: "Emergency infrastructure and supplies during floods" },
    { indicator: 44, capital: 'physical', resilience: 'rapidity', name: "Emergency infrastructure and supplies during heatwaves" },
    { indicator: 45, capital: 'physical', resilience: 'robustness', name: "Continuity of healthcare during disaster during floods" },
    { indicator: 46, capital: 'physical', resilience: 'robustness', name: "Continuity of healthcare during disaster during heatwaves" },
    { indicator: 47, capital: 'physical', resilience: 'rapidity', name: "Forecasting for floods" },
    { indicator: 48, capital: 'physical', resilience: 'rapidity', name: "Forecasting for heatwaves" },
    { indicator: 49, capital: 'physical', resilience: 'robustness', name: "Household protection and adaptation on floods" },
    { indicator: 50, capital: 'physical', resilience: 'robustness', name: "Household protection and adaptation on heatwaves" },
    { indicator: 51, capital: 'physical', resilience: 'robustness', name: "Availability of clean, safe water during floods" },
    { indicator: 52, capital: 'physical', resilience: 'robustness', name: "Availability of clean, safe water during heatwaves" },
    { indicator: 53, capital: 'physical', resilience: 'robustness', name: "Waste management and risk" },
    { indicator: 54, capital: 'physical', resilience: 'robustness', name: "Large scale flood protection" },
    { indicator: 55, capital: 'social', resilience: 'resourcefulness', name: "Mutual support" },
    { indicator: 56, capital: 'social', resilience: 'resourcefulness', name: "Social inclusiveness of disaster risk management" },
    { indicator: 57, capital: 'social', resilience: 'robustness', name: "Community safety" },
    { indicator: 58, capital: 'social', resilience: 'resourcefulness', name: "Local leadership" },
    { indicator: 59, capital: 'social', resilience: 'robustness', name: "Disaster response personnel" },
    { indicator: 60, capital: 'social', resilience: 'robustness', name: "Healthcare accessibility" },
    { indicator: 61, capital: 'social', resilience: 'resourcefulness', name: "Trust in local authorities" },
    { indicator: 62, capital: 'social', resilience: 'resourcefulness', name: "Intra-community equity" },
    { indicator: 63, capital: 'social', resilience: 'resourcefulness', name: "Inter-community equity" },
    { indicator: 64, capital: 'social', resilience: 'rapidity', name: "Risk reduction planning for floods" },
    { indicator: 65, capital: 'social', resilience: 'rapidity', name: "Risk reduction planning for heatwaves" },
    { indicator: 66, capital: 'social', resilience: 'rapidity', name: "Response planning for floods" },
    { indicator: 67, capital: 'social', resilience: 'rapidity', name: "Response planning for heatwaves" },
    { indicator: 68, capital: 'social', resilience: 'robustness', name: "Family violence and response planning during floods" },
    { indicator: 69, capital: 'social', resilience: 'robustness', name: "Family violence and response planning during heatwaves" },
    { indicator: 70, capital: 'social', resilience: 'resourcefulness', name: "Stakeholder engagement in risk management for floods" },
    { indicator: 71, capital: 'social', resilience: 'resourcefulness', name: "Stakeholder engagement in risk management for heatwaves" },
    { indicator: 72, capital: 'social', resilience: 'rapidity', name: "Flood risk mapping" },
    { indicator: 73, capital: 'social', resilience: 'rapidity', name: "Heatwave risk mapping" },
    { indicator: 74, capital: 'social', resilience: 'resourcefulness', name: "Flood disaster impact data collection and use" },
    { indicator: 75, capital: 'social', resilience: 'resourcefulness', name: "Heatwave disaster impact data collection and use" }
];